name: Build integrity

on:
  pull_request:
    branches:
      - release

jobs:
  build-intergrity:
    runs-on: ubuntu-latest
    steps:
      - name: Prefix pull request title
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^[a-z]+$'
          allowed_prefixes: 'feat,fix,docs,style,refactor,perf,test,build,ci,chore,revert'
          prefix_case_sensitive: true
          github_token: ${{ github.token }}

      - uses: actions/checkout@v4
      - name: Check build integrity
        run: |
          npm install
          npm run lint:prettier
